# Generated by Django 4.1.2 on 2022-10-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='agent',
            new_name='lead_owner',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('not contacted', 'Not Contacted'), ('attempted to contact', 'Attempted to Contact'), ('validated', 'Validated'), ('need to visit', 'Need to Visit'), ('need to visit high priority', 'Need to Visit High Priority'), ('tried for appointment', 'Tried for Appointment'), ('appointment scheduled', 'Appointment Scheduled'), ('need time', 'Need Time'), ('junk lead on call', 'Junk Lead on Call'), ('premium valid architects', 'Premium Valid Architects'), ('visited 1', 'Visited 1'), ('visited premium valid architects', 'Visited Premium Valid Architects'), ('call 1', 'Call 1'), ('need to visit 2', 'Need to Visit 2'), ('tried for appointment for visit 2', 'Tried for Appointment for Visit 2'), ('appointment scheduled 2', 'Appointment Scheduled 2'), ('visited 2', 'Visited 2'), ('call 2', 'call 2'), ('need to visit 3', 'Need to Visit 3'), ('tried for appointment for visit 3', 'Tried for Appointment for Visit 3'), ('appointment scheduled 3', 'Appointment Scheduled 3'), ('visited 3', 'Visited 3'), ('call 3', 'call 3'), ('need to visit 4', 'Need to Visit 4'), ('tried for appointment for visit 4', 'Tried for Appointment for Visit 4'), ('appointment scheduled 4', 'Appointment Scheduled 4'), ('visited 4', 'Visited 4'), ('call 4', 'call 4'), ('will refer projects', 'will refer projects'), ('no response', 'No Response'), ('junk lead on visit', 'Junk Lead on Visit')], max_length=150, null=True),
        ),
    ]
