# Generated by Django 4.1.2 on 2022-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_rename_agent_lead_lead_owner_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='appointment_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('web research , subject expert magazine/blog', 'Web Research , Subject Expert Magazine/Blog'), ('facebook advertisement', 'Facebook Advertisement'), ('hunting', 'Hunting'), ('existing customer reference', 'Existing Customer Reference'), ('linkedIn', 'LinkedIn'), ('google adwords', 'Google Adwords'), ('pinterest', 'Pinterest'), ('instagram', 'Instagram'), ('referrals', 'Referrals'), ('associates', 'Associates'), ('site reference', 'Site Reference'), ('association programes', 'Association programes'), ('architect reference', 'Architect Reference'), ('electrical consultant reference', 'Electrical Consultant Reference'), ('electrical contractor reference', 'Electrical Contractor Reference'), ('interior designer reference', 'Interior Designer Reference'), ('inbound', 'Inbound'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=150, null=True),
        ),
    ]
