# Generated by Django 4.1.2 on 2022-10-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_appointment_day_lead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ad_source',
            field=models.CharField(blank=True, choices=[('amber display', 'Amber Display'), ('amber fb', 'Amber FB'), ('amber remark', 'Amber Remark'), ('amber search', 'Amber Search'), ('amber yt', 'Amber YT'), ('display', 'Display'), ('remarketing', 'Remarketing'), ('search', 'Search'), ('video', 'Video')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, choices=[("Architect's Firm", "Architect's Firm"), ('Customer', 'Customer'), ("Interior Designer's Firm", "Interior Designer's Firm"), ('Electrical Consultant / MEP', 'Electrical Consultant / MEP'), ('Electrical Contractors', 'Electrical Contractors'), ('Electrical Shop Owner', 'Electrical Shop Owner'), ('Civil Engineer', 'Civil Engineer'), ('Civil Contractors', 'Civil Contractors'), ('Premium Electrician', 'Premium Electrician'), ('Small Scale Builders', 'Small Scale Builders'), ('Large Scale Builders', 'Large Scale Builders'), ('Dealer', 'Dealer'), ('Electrician', 'Electrician'), ('General Workers', 'General Workers'), ('Integrators', 'Integrators'), ('PMC', 'PMC')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, choices=[('p architect', 'P Architect'), ('architect', 'Architect'), ('junior architect', 'Junior Architect'), ('project coordinator', 'Project coordinator'), ('electrical consultant', 'Electrical Consultant'), ('electrical contractor', 'Electrical Contractor'), ('Interior Designer', 'Interior Designer'), ('Electrician', 'Electrician')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_response',
            field=models.CharField(blank=True, choices=[('High Interest', 'High Interest'), ('Medium Interest', 'Medium Interest'), ('Low Interest', 'Low Interest'), ('Neutral', 'Neutral'), ('Not Interested', 'Not Interested')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('normal', 'Normal')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tier',
            field=models.CharField(blank=True, choices=[('Tier A+', 'Tier A+'), ('Tier A', 'Tier A'), ('Tier B', 'Tier B'), ('Tier C', 'Tier C')], max_length=150, null=True),
        ),
    ]
