# Generated by Django 4.1.2 on 2022-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_lead_facebook_ad_lead_fb_ad_campaign_lead_fb_ad_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sec_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
