# Generated by Django 4.1.2 on 2022-10-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_rename_sec_email_lead_secondary_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
