# Generated by Django 4.1.2 on 2022-10-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Principal Architect', 'Principal Architect'), ('Principal Designer', 'Principal Designer'), ('Executive Director', 'Executive Director'), ('Co-Founder', 'Co-Founder'), ('Architect', 'Architect'), ('Admin', 'Admin'), ('HR', 'HR'), ('Junior Architect', 'Junior Architect'), ('Senior Architect', 'Senior Architect'), ('Senior Consultant', 'Senior Consultant'), ('Project Coordinator', 'Project Coordinator'), ('Principal Consultant', 'Principal Consultant'), ('Proprietor', 'Proprietor'), ('Director', 'Director'), ('Manager', 'Manager'), ('Person In charge', 'Person In charge'), ('CEO', 'CEO'), ('Founder and Chairman', 'Founder and Chairman'), ('Chief Architect', 'Chief Architect'), ('Managing Director', 'Managing Director'), ('Project Head', 'Project Head'), ('Project Director', 'Project Director'), ('Project Manager', 'Project Manager'), ('Associate', 'Associate'), ('Project Associate', 'Project Associate'), ('Interior Designer', 'Interior Designer'), ('Partner', 'Partner'), ('Chief Designer', 'Chief Designer')], max_length=150, null=True),
        ),
    ]
