# Generated by Django 4.1.2 on 2022-10-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acccount_name',
            new_name='account_name',
        ),
    ]
