# Generated by Django 4.1.2 on 2022-10-13 08:47

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_acccount_name_account_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_call_date', models.DateTimeField(blank=True, null=True)),
                ('last_connected_call_date', models.DateField(blank=True, null=True)),
                ('last_chat_date', models.DateField(blank=True, null=True)),
                ('last_meeting_date', models.DateField(blank=True, null=True)),
                ('cf_account_status', models.CharField(blank=True, choices=[('Not yet Visited', 'Not yet Visited'), ('Neutral', 'Neutral'), ('Considering CF', 'Considering CF'), ('Will Refer', 'Will Refer'), ('Associated with CF', 'Associated with CF'), ('Will Consider', 'Will Consider'), ('Not Interested', 'Not Interested'), ('Associated with Competitor', 'Associated with Competitor'), ('Need To Boost', 'Need To Boost'), ('Lost Account', 'Lost Account'), ('Permanant Lost Account', 'Permanant Lost Account'), ('Junk', 'Junk')], max_length=150, null=True)),
                ('follow_up_status', models.CharField(blank=True, choices=[('not contacted', 'Not Contacted'), ('not contacted high priority', 'Not Contacted High Priority'), ('Attempted to Contact', 'Attempted to Contact'), ('Need to Visit 1', 'Need to Visit 1'), ('Tried For Appointment 1', 'Tried For Appointment 1'), ('Appointment Scheduled 1', 'Appointment Scheduled 1'), ('visited 1', 'Visited 1'), ('call 1', 'call 1'), ('Need to Visit 2', 'Need to Visit 2'), ('tried for appointment 2', 'Tried for Appointment 2'), ('appointment scheduled 2', 'Appointment Scheduled 2'), ('visited 2', 'Visited 2'), ('call 2', 'call 2'), ('need to visit 3', 'Need to Visit 3'), ('tried for appointment 3', 'Tried for Appointment 3'), ('appointment scheduled 3', 'Appointment Scheduled 3'), ('visited 3', 'Visited 3'), ('call 3', 'call 3'), ('need to visit 4', 'Need to Visit 4'), ('tried for appointment 4', 'Tried for Appointment 4'), ('appointment scheduled 4', 'Appointment Scheduled 4'), ('visited 4', 'Visited 4'), ('call 4', 'call 4'), ('need to visit 5', 'Need to Visit 5'), ('tried for appointment 5', 'Tried for Appointment 5'), ('appointment scheduled 5', 'Appointment Scheduled 5'), ('visited 5', 'Visited 5'), ('call 5', 'call 5'), ('need to visit 5', 'Need to Visit 5'), ('tried for appointment 5', 'Tried for Appointment 5'), ('appointment scheduled 5', 'Appointment Scheduled 5'), ('visited 5', 'Visited 5'), ('call 5', 'call 5')], max_length=150, null=True)),
                ('last_project_ref', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=accounts.models.handle_upload_follow_ups)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='accounts.account')),
            ],
        ),
    ]
