# Generated by Django 4.1.2 on 2022-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_birthday_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='follow_up_files/'),
        ),
    ]
