import pytz
from django.utils.translation import gettext_lazy as _


INDCHOICES = (
    ("ADVERTISING", "ADVERTISING"),
    ("AGRICULTURE", "AGRICULTURE"),
    ("APPAREL & ACCESSORIES", "APPAREL & ACCESSORIES"),
    ("AUTOMOTIVE", "AUTOMOTIVE"),
    ("BANKING", "BANKING"),
    ("BIOTECHNOLOGY", "BIOTECHNOLOGY"),
    ("BUILDING MATERIALS & EQUIPMENT", "BUILDING MATERIALS & EQUIPMENT"),
    ("CHEMICAL", "CHEMICAL"),
    ("COMPUTER", "COMPUTER"),
    ("EDUCATION", "EDUCATION"),
    ("ELECTRONICS", "ELECTRONICS"),
    ("ENERGY", "ENERGY"),
    ("ENTERTAINMENT & LEISURE", "ENTERTAINMENT & LEISURE"),
    ("FINANCE", "FINANCE"),
    ("FOOD & BEVERAGE", "FOOD & BEVERAGE"),
    ("GROCERY", "GROCERY"),
    ("HEALTHCARE", "HEALTHCARE"),
    ("INSURANCE", "INSURANCE"),
    ("LEGAL", "LEGAL"),
    ("MANUFACTURING", "MANUFACTURING"),
    ("PUBLISHING", "PUBLISHING"),
    ("REAL ESTATE", "REAL ESTATE"),
    ("SERVICE", "SERVICE"),
    ("SOFTWARE", "SOFTWARE"),
    ("SPORTS", "SPORTS"),
    ("TECHNOLOGY", "TECHNOLOGY"),
    ("TELECOMMUNICATIONS", "TELECOMMUNICATIONS"),
    ("TELEVISION", "TELEVISION"),
    ("TRANSPORTATION", "TRANSPORTATION"),
    ("VENTURE CAPITAL", "VENTURE CAPITAL"),
)

TYPECHOICES = (
    ("CUSTOMER", "CUSTOMER"),
    ("INVESTOR", "INVESTOR"),
    ("PARTNER", "PARTNER"),
    ("RESELLER", "RESELLER"),
)

ROLES = (
    ("ADMIN", "ADMIN"),
    ("USER", "USER"),
)

LEAD_STATUS = (
    ("not contacted", "Not Contacted"),
    ("attempted to contact", "Attempted to Contact"),
    ("validated", "Validated"),
    ("need to visit", "Need to Visit"),
    ("need to visit high priority", "Need to Visit High Priority"),
    ("tried for appointment", "Tried for Appointment"),
    ("appointment scheduled", "Appointment Scheduled"),
    ("need time", "Need Time"),
    ("junk lead on call", "Junk Lead on Call"),
    ("premium valid architects", "Premium Valid Architects"),
    ("visited 1", "Visited 1"),
    ("visited premium valid architects", "Visited Premium Valid Architects"),
    ("call 1", "Call 1"),
    ("need to visit 2", "Need to Visit 2"),
    ("tried for appointment for visit 2", "Tried for Appointment for Visit 2"),
    ("appointment scheduled 2", "Appointment Scheduled 2"),
    ("visited 2", "Visited 2"),
    ("call 2", "call 2"),
    ("need to visit 3", "Need to Visit 3"),
    ("tried for appointment for visit 3", "Tried for Appointment for Visit 3"),
    ("appointment scheduled 3", "Appointment Scheduled 3"),
    ("visited 3", "Visited 3"),
    ("call 3", "call 3"),
    ("need to visit 4", "Need to Visit 4"),
    ("tried for appointment for visit 4", "Tried for Appointment for Visit 4"),
    ("appointment scheduled 4", "Appointment Scheduled 4"),
    ("visited 4", "Visited 4"),
    ("call 4", "call 4"),
    ("will refer projects", "will refer projects"),
    ("no response", "No Response"),
    ("junk lead on visit", "Junk Lead on Visit"),

)


LEAD_SOURCE = (
    ("web research , subject expert magazine/blog", "Web Research , Subject Expert Magazine/Blog"),
    ("facebook advertisement", "Facebook Advertisement"),
    ("hunting", "Hunting"),
    ("existing customer reference", "Existing Customer Reference"),
    ("linkedIn", "LinkedIn"),
    ("google adwords", "Google Adwords"),
    ("pinterest", "Pinterest"),
    ("instagram", "Instagram"),
    ("referrals", "Referrals"),
    ("associates", "Associates"),
    ("site reference", "Site Reference"),
    ("association programes", "Association programes"),
    ("architect reference", "Architect Reference"),
    ("electrical consultant reference", "Electrical Consultant Reference"),
    ("electrical contractor reference", "Electrical Contractor Reference"),
    ("interior designer reference", "Interior Designer Reference"),
    ("inbound", "Inbound"),
    ("facebook", "Facebook"),
    ("twitter", "Twitter"),
)

STATUS_CHOICE = (
    ("New", "New"),
    ("Assigned", "Assigned"),
    ("Pending", "Pending"),
    ("Closed", "Closed"),
    ("Rejected", "Rejected"),
    ("Duplicate", "Duplicate"),
)

PRIORITY_CHOICE = (
    ("Low", "Low"),
    ("Normal", "Normal"),
    ("High", "High"),
    ("Urgent", "Urgent"),
)

CASE_TYPE = (("Question", "Question"), ("Incident", "Incident"), ("Problem", "Problem"))

STAGES = (
    ("QUALIFICATION", "QUALIFICATION"),
    ("NEEDS ANALYSIS", "NEEDS ANALYSIS"),
    ("VALUE PROPOSITION", "VALUE PROPOSITION"),
    ("ID.DECISION MAKERS", "ID.DECISION MAKERS"),
    ("PERCEPTION ANALYSIS", "PERCEPTION ANALYSIS"),
    ("PROPOSAL/PRICE QUOTE", "PROPOSAL/PRICE QUOTE"),
    ("NEGOTIATION/REVIEW", "NEGOTIATION/REVIEW"),
    ("CLOSED WON", "CLOSED WON"),
    ("CLOSED LOST", "CLOSED LOST"),
)

SOURCES = (
    ("NONE", "NONE"),
    ("CALL", "CALL"),
    ("EMAIL", " EMAIL"),
    ("EXISTING CUSTOMER", "EXISTING CUSTOMER"),
    ("PARTNER", "PARTNER"),
    ("PUBLIC RELATIONS", "PUBLIC RELATIONS"),
    ("CAMPAIGN", "CAMPAIGN"),
    ("WEBSITE", "WEBSITE"),
    ("OTHER", "OTHER"),
)

EVENT_PARENT_TYPE = ((10, "Account"), (13, "Lead"), (14, "Opportunity"), (11, "Case"))

EVENT_STATUS = (
    ("Planned", "Planned"),
    ("Held", "Held"),
    ("Not Held", "Not Held"),
    ("Not Started", "Not Started"),
    ("Started", "Started"),
    ("Completed", "Completed"),
    ("Canceled", "Canceled"),
    ("Deferred", "Deferred"),
)


COUNTRIES = (
    ("GB", _("United Kingdom")),
    ("AF", _("Afghanistan")),
    ("AX", _("Aland Islands")),
    ("AL", _("Albania")),
    ("DZ", _("Algeria")),
    ("AS", _("American Samoa")),
    ("AD", _("Andorra")),
    ("AO", _("Angola")),
    ("AI", _("Anguilla")),
    ("AQ", _("Antarctica")),
    ("AG", _("Antigua and Barbuda")),
    ("AR", _("Argentina")),
    ("AM", _("Armenia")),
    ("AW", _("Aruba")),
    ("AU", _("Australia")),
    ("AT", _("Austria")),
    ("AZ", _("Azerbaijan")),
    ("BS", _("Bahamas")),
    ("BH", _("Bahrain")),
    ("BD", _("Bangladesh")),
    ("BB", _("Barbados")),
    ("BY", _("Belarus")),
    ("BE", _("Belgium")),
    ("BZ", _("Belize")),
    ("BJ", _("Benin")),
    ("BM", _("Bermuda")),
    ("BT", _("Bhutan")),
    ("BO", _("Bolivia")),
    ("BA", _("Bosnia and Herzegovina")),
    ("BW", _("Botswana")),
    ("BV", _("Bouvet Island")),
    ("BR", _("Brazil")),
    ("IO", _("British Indian Ocean Territory")),
    ("BN", _("Brunei Darussalam")),
    ("BG", _("Bulgaria")),
    ("BF", _("Burkina Faso")),
    ("BI", _("Burundi")),
    ("KH", _("Cambodia")),
    ("CM", _("Cameroon")),
    ("CA", _("Canada")),
    ("CV", _("Cape Verde")),
    ("KY", _("Cayman Islands")),
    ("CF", _("Central African Republic")),
    ("TD", _("Chad")),
    ("CL", _("Chile")),
    ("CN", _("China")),
    ("CX", _("Christmas Island")),
    ("CC", _("Cocos (Keeling) Islands")),
    ("CO", _("Colombia")),
    ("KM", _("Comoros")),
    ("CG", _("Congo")),
    ("CD", _("Congo, The Democratic Republic of the")),
    ("CK", _("Cook Islands")),
    ("CR", _("Costa Rica")),
    ("CI", _("Cote d'Ivoire")),
    ("HR", _("Croatia")),
    ("CU", _("Cuba")),
    ("CY", _("Cyprus")),
    ("CZ", _("Czech Republic")),
    ("DK", _("Denmark")),
    ("DJ", _("Djibouti")),
    ("DM", _("Dominica")),
    ("DO", _("Dominican Republic")),
    ("EC", _("Ecuador")),
    ("EG", _("Egypt")),
    ("SV", _("El Salvador")),
    ("GQ", _("Equatorial Guinea")),
    ("ER", _("Eritrea")),
    ("EE", _("Estonia")),
    ("ET", _("Ethiopia")),
    ("FK", _("Falkland Islands (Malvinas)")),
    ("FO", _("Faroe Islands")),
    ("FJ", _("Fiji")),
    ("FI", _("Finland")),
    ("FR", _("France")),
    ("GF", _("French Guiana")),
    ("PF", _("French Polynesia")),
    ("TF", _("French Southern Territories")),
    ("GA", _("Gabon")),
    ("GM", _("Gambia")),
    ("GE", _("Georgia")),
    ("DE", _("Germany")),
    ("GH", _("Ghana")),
    ("GI", _("Gibraltar")),
    ("GR", _("Greece")),
    ("GL", _("Greenland")),
    ("GD", _("Grenada")),
    ("GP", _("Guadeloupe")),
    ("GU", _("Guam")),
    ("GT", _("Guatemala")),
    ("GG", _("Guernsey")),
    ("GN", _("Guinea")),
    ("GW", _("Guinea-Bissau")),
    ("GY", _("Guyana")),
    ("HT", _("Haiti")),
    ("HM", _("Heard Island and McDonald Islands")),
    ("VA", _("Holy See (Vatican City State)")),
    ("HN", _("Honduras")),
    ("HK", _("Hong Kong")),
    ("HU", _("Hungary")),
    ("IS", _("Iceland")),
    ("IN", _("India")),
    ("ID", _("Indonesia")),
    ("IR", _("Iran, Islamic Republic of")),
    ("IQ", _("Iraq")),
    ("IE", _("Ireland")),
    ("IM", _("Isle of Man")),
    ("IL", _("Israel")),
    ("IT", _("Italy")),
    ("JM", _("Jamaica")),
    ("JP", _("Japan")),
    ("JE", _("Jersey")),
    ("JO", _("Jordan")),
    ("KZ", _("Kazakhstan")),
    ("KE", _("Kenya")),
    ("KI", _("Kiribati")),
    ("KP", _("Korea, Democratic People's Republic of")),
    ("KR", _("Korea, Republic of")),
    ("KW", _("Kuwait")),
    ("KG", _("Kyrgyzstan")),
    ("LA", _("Lao People's Democratic Republic")),
    ("LV", _("Latvia")),
    ("LB", _("Lebanon")),
    ("LS", _("Lesotho")),
    ("LR", _("Liberia")),
    ("LY", _("Libyan Arab Jamahiriya")),
    ("LI", _("Liechtenstein")),
    ("LT", _("Lithuania")),
    ("LU", _("Luxembourg")),
    ("MO", _("Macao")),
    ("MK", _("Macedonia, The Former Yugoslav Republic of")),
    ("MG", _("Madagascar")),
    ("MW", _("Malawi")),
    ("MY", _("Malaysia")),
    ("MV", _("Maldives")),
    ("ML", _("Mali")),
    ("MT", _("Malta")),
    ("MH", _("Marshall Islands")),
    ("MQ", _("Martinique")),
    ("MR", _("Mauritania")),
    ("MU", _("Mauritius")),
    ("YT", _("Mayotte")),
    ("MX", _("Mexico")),
    ("FM", _("Micronesia, Federated States of")),
    ("MD", _("Moldova")),
    ("MC", _("Monaco")),
    ("MN", _("Mongolia")),
    ("ME", _("Montenegro")),
    ("MS", _("Montserrat")),
    ("MA", _("Morocco")),
    ("MZ", _("Mozambique")),
    ("MM", _("Myanmar")),
    ("NA", _("Namibia")),
    ("NR", _("Nauru")),
    ("NP", _("Nepal")),
    ("NL", _("Netherlands")),
    ("AN", _("Netherlands Antilles")),
    ("NC", _("New Caledonia")),
    ("NZ", _("New Zealand")),
    ("NI", _("Nicaragua")),
    ("NE", _("Niger")),
    ("NG", _("Nigeria")),
    ("NU", _("Niue")),
    ("NF", _("Norfolk Island")),
    ("MP", _("Northern Mariana Islands")),
    ("NO", _("Norway")),
    ("OM", _("Oman")),
    ("PK", _("Pakistan")),
    ("PW", _("Palau")),
    ("PS", _("Palestinian Territory, Occupied")),
    ("PA", _("Panama")),
    ("PG", _("Papua New Guinea")),
    ("PY", _("Paraguay")),
    ("PE", _("Peru")),
    ("PH", _("Philippines")),
    ("PN", _("Pitcairn")),
    ("PL", _("Poland")),
    ("PT", _("Portugal")),
    ("PR", _("Puerto Rico")),
    ("QA", _("Qatar")),
    ("RE", _("Reunion")),
    ("RO", _("Romania")),
    ("RU", _("Russian Federation")),
    ("RW", _("Rwanda")),
    ("BL", _("Saint Barthelemy")),
    ("SH", _("Saint Helena")),
    ("KN", _("Saint Kitts and Nevis")),
    ("LC", _("Saint Lucia")),
    ("MF", _("Saint Martin")),
    ("PM", _("Saint Pierre and Miquelon")),
    ("VC", _("Saint Vincent and the Grenadines")),
    ("WS", _("Samoa")),
    ("SM", _("San Marino")),
    ("ST", _("Sao Tome and Principe")),
    ("SA", _("Saudi Arabia")),
    ("SN", _("Senegal")),
    ("RS", _("Serbia")),
    ("SC", _("Seychelles")),
    ("SL", _("Sierra Leone")),
    ("SG", _("Singapore")),
    ("SK", _("Slovakia")),
    ("SI", _("Slovenia")),
    ("SB", _("Solomon Islands")),
    ("SO", _("Somalia")),
    ("ZA", _("South Africa")),
    ("GS", _("South Georgia and the South Sandwich Islands")),
    ("ES", _("Spain")),
    ("LK", _("Sri Lanka")),
    ("SD", _("Sudan")),
    ("SR", _("Suriname")),
    ("SJ", _("Svalbard and Jan Mayen")),
    ("SZ", _("Swaziland")),
    ("SE", _("Sweden")),
    ("CH", _("Switzerland")),
    ("SY", _("Syrian Arab Republic")),
    ("TW", _("Taiwan, Province of China")),
    ("TJ", _("Tajikistan")),
    ("TZ", _("Tanzania, United Republic of")),
    ("TH", _("Thailand")),
    ("TL", _("Timor-Leste")),
    ("TG", _("Togo")),
    ("TK", _("Tokelau")),
    ("TO", _("Tonga")),
    ("TT", _("Trinidad and Tobago")),
    ("TN", _("Tunisia")),
    ("TR", _("Turkey")),
    ("TM", _("Turkmenistan")),
    ("TC", _("Turks and Caicos Islands")),
    ("TV", _("Tuvalu")),
    ("UG", _("Uganda")),
    ("UA", _("Ukraine")),
    ("AE", _("United Arab Emirates")),
    ("US", _("United States")),
    ("UM", _("United States Minor Outlying Islands")),
    ("UY", _("Uruguay")),
    ("UZ", _("Uzbekistan")),
    ("VU", _("Vanuatu")),
    ("VE", _("Venezuela")),
    ("VN", _("Viet Nam")),
    ("VG", _("Virgin Islands, British")),
    ("VI", _("Virgin Islands, U.S.")),
    ("WF", _("Wallis and Futuna")),
    ("EH", _("Western Sahara")),
    ("YE", _("Yemen")),
    ("ZM", _("Zambia")),
    ("ZW", _("Zimbabwe")),
)

CURRENCY_CODES = (
    ("AED", _("AED, Dirham")),
    ("AFN", _("AFN, Afghani")),
    ("ALL", _("ALL, Lek")),
    ("AMD", _("AMD, Dram")),
    ("ANG", _("ANG, Guilder")),
    ("AOA", _("AOA, Kwanza")),
    ("ARS", _("ARS, Peso")),
    ("AUD", _("AUD, Dollar")),
    ("AWG", _("AWG, Guilder")),
    ("AZN", _("AZN, Manat")),
    ("BAM", _("BAM, Marka")),
    ("BBD", _("BBD, Dollar")),
    ("BDT", _("BDT, Taka")),
    ("BGN", _("BGN, Lev")),
    ("BHD", _("BHD, Dinar")),
    ("BIF", _("BIF, Franc")),
    ("BMD", _("BMD, Dollar")),
    ("BND", _("BND, Dollar")),
    ("BOB", _("BOB, Boliviano")),
    ("BRL", _("BRL, Real")),
    ("BSD", _("BSD, Dollar")),
    ("BTN", _("BTN, Ngultrum")),
    ("BWP", _("BWP, Pula")),
    ("BYR", _("BYR, Ruble")),
    ("BZD", _("BZD, Dollar")),
    ("CAD", _("CAD, Dollar")),
    ("CDF", _("CDF, Franc")),
    ("CHF", _("CHF, Franc")),
    ("CLP", _("CLP, Peso")),
    ("CNY", _("CNY, Yuan Renminbi")),
    ("COP", _("COP, Peso")),
    ("CRC", _("CRC, Colon")),
    ("CUP", _("CUP, Peso")),
    ("CVE", _("CVE, Escudo")),
    ("CZK", _("CZK, Koruna")),
    ("DJF", _("DJF, Franc")),
    ("DKK", _("DKK, Krone")),
    ("DOP", _("DOP, Peso")),
    ("DZD", _("DZD, Dinar")),
    ("EGP", _("EGP, Pound")),
    ("ERN", _("ERN, Nakfa")),
    ("ETB", _("ETB, Birr")),
    ("EUR", _("EUR, Euro")),
    ("FJD", _("FJD, Dollar")),
    ("FKP", _("FKP, Pound")),
    ("GBP", _("GBP, Pound")),
    ("GEL", _("GEL, Lari")),
    ("GHS", _("GHS, Cedi")),
    ("GIP", _("GIP, Pound")),
    ("GMD", _("GMD, Dalasi")),
    ("GNF", _("GNF, Franc")),
    ("GTQ", _("GTQ, Quetzal")),
    ("GYD", _("GYD, Dollar")),
    ("HKD", _("HKD, Dollar")),
    ("HNL", _("HNL, Lempira")),
    ("HRK", _("HRK, Kuna")),
    ("HTG", _("HTG, Gourde")),
    ("HUF", _("HUF, Forint")),
    ("IDR", _("IDR, Rupiah")),
    ("ILS", _("ILS, Shekel")),
    ("INR", _("INR, Rupee")),
    ("IQD", _("IQD, Dinar")),
    ("IRR", _("IRR, Rial")),
    ("ISK", _("ISK, Krona")),
    ("JMD", _("JMD, Dollar")),
    ("JOD", _("JOD, Dinar")),
    ("JPY", _("JPY, Yen")),
    ("KES", _("KES, Shilling")),
    ("KGS", _("KGS, Som")),
    ("KHR", _("KHR, Riels")),
    ("KMF", _("KMF, Franc")),
    ("KPW", _("KPW, Won")),
    ("KRW", _("KRW, Won")),
    ("KWD", _("KWD, Dinar")),
    ("KYD", _("KYD, Dollar")),
    ("KZT", _("KZT, Tenge")),
    ("LAK", _("LAK, Kip")),
    ("LBP", _("LBP, Pound")),
    ("LKR", _("LKR, Rupee")),
    ("LRD", _("LRD, Dollar")),
    ("LSL", _("LSL, Loti")),
    ("LTL", _("LTL, Litas")),
    ("LVL", _("LVL, Lat")),
    ("LYD", _("LYD, Dinar")),
    ("MAD", _("MAD, Dirham")),
    ("MDL", _("MDL, Leu")),
    ("MGA", _("MGA, Ariary")),
    ("MKD", _("MKD, Denar")),
    ("MMK", _("MMK, Kyat")),
    ("MNT", _("MNT, Tugrik")),
    ("MOP", _("MOP, Pataca")),
    ("MRO", _("MRO, Ouguiya")),
    ("MUR", _("MUR, Rupee")),
    ("MVR", _("MVR, Rufiyaa")),
    ("MWK", _("MWK, Kwacha")),
    ("MXN", _("MXN, Peso")),
    ("MYR", _("MYR, Ringgit")),
    ("MZN", _("MZN, Metical")),
    ("NAD", _("NAD, Dollar")),
    ("NGN", _("NGN, Naira")),
    ("NIO", _("NIO, Cordoba")),
    ("NOK", _("NOK, Krone")),
    ("NPR", _("NPR, Rupee")),
    ("NZD", _("NZD, Dollar")),
    ("OMR", _("OMR, Rial")),
    ("PAB", _("PAB, Balboa")),
    ("PEN", _("PEN, Sol")),
    ("PGK", _("PGK, Kina")),
    ("PHP", _("PHP, Peso")),
    ("PKR", _("PKR, Rupee")),
    ("PLN", _("PLN, Zloty")),
    ("PYG", _("PYG, Guarani")),
    ("QAR", _("QAR, Rial")),
    ("RON", _("RON, Leu")),
    ("RSD", _("RSD, Dinar")),
    ("RUB", _("RUB, Ruble")),
    ("RWF", _("RWF, Franc")),
    ("SAR", _("SAR, Rial")),
    ("SBD", _("SBD, Dollar")),
    ("SCR", _("SCR, Rupee")),
    ("SDG", _("SDG, Pound")),
    ("SEK", _("SEK, Krona")),
    ("SGD", _("SGD, Dollar")),
    ("SHP", _("SHP, Pound")),
    ("SLL", _("SLL, Leone")),
    ("SOS", _("SOS, Shilling")),
    ("SRD", _("SRD, Dollar")),
    ("SSP", _("SSP, Pound")),
    ("STD", _("STD, Dobra")),
    ("SYP", _("SYP, Pound")),
    ("SZL", _("SZL, Lilangeni")),
    ("THB", _("THB, Baht")),
    ("TJS", _("TJS, Somoni")),
    ("TMT", _("TMT, Manat")),
    ("TND", _("TND, Dinar")),
    ("TOP", _("TOP, Paanga")),
    ("TRY", _("TRY, Lira")),
    ("TTD", _("TTD, Dollar")),
    ("TWD", _("TWD, Dollar")),
    ("TZS", _("TZS, Shilling")),
    ("UAH", _("UAH, Hryvnia")),
    ("UGX", _("UGX, Shilling")),
    ("USD", _("$, Dollar")),
    ("UYU", _("UYU, Peso")),
    ("UZS", _("UZS, Som")),
    ("VEF", _("VEF, Bolivar")),
    ("VND", _("VND, Dong")),
    ("VUV", _("VUV, Vatu")),
    ("WST", _("WST, Tala")),
    ("XAF", _("XAF, Franc")),
    ("XCD", _("XCD, Dollar")),
    ("XOF", _("XOF, Franc")),
    ("XPF", _("XPF, Franc")),
    ("YER", _("YER, Rial")),
    ("ZAR", _("ZAR, Rand")),
    ("ZMK", _("ZMK, Kwacha")),
    ("ZWL", _("ZWL, Dollar")),
)

STATES = (("Andhra Pradesh","Andhra Pradesh"),
            ("Arunachal Pradesh ","Arunachal Pradesh "),
            ("Assam","Assam"),
            ("Bihar","Bihar"),
            ("Chhattisgarh","Chhattisgarh"),
            ("Goa","Goa"),
            ("Gujarat","Gujarat"),
            ("Haryana","Haryana"),
            ("Himachal Pradesh","Himachal Pradesh"),
            ("Jammu and Kashmir ","Jammu and Kashmir "),
            ("Jharkhand","Jharkhand"),
            ("Karnataka","Karnataka"),
            ("Kerala","Kerala"),
            ("Madhya Pradesh","Madhya Pradesh"),
            ("Maharashtra","Maharashtra"),
            ("Manipur","Manipur"),
            ("Meghalaya","Meghalaya"),
            ("Mizoram","Mizoram"),
            ("Nagaland","Nagaland"),
            ("Odisha","Odisha"),
            ("Punjab","Punjab"),
            ("Rajasthan","Rajasthan"),
            ("Sikkim","Sikkim"),
            ("Tamil Nadu","Tamil Nadu"),
            ("Telangana","Telangana"),
            ("Tripura","Tripura"),
            ("Uttar Pradesh","Uttar Pradesh"),
            ("Uttarakhand","Uttarakhand"),
            ("West Bengal","West Bengal"),
            ("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),
            ("Chandigarh","Chandigarh"),
            ("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),
            ("Daman and Diu","Daman and Diu"),
            ("Lakshadweep","Lakshadweep"),
            ("New Delhi","New Delhi"),
            ("Puducherry","Puducherry"))


DISTRICTS = (
            ("Alappuzha","Alappuzha"),
            ("Ariyalur","Ariyalur"),
            ("Anantapur","Anantapur"),
            ("Ahmednagar","Ahmednagar"),
            ("Akola","Akola"),
            ("Amravati","Amravati"),
            ("Aurangabad","Aurangabad"),
            ("Beed","Beed"),
            ("Bhandara","Bhandara"),
            ("Buldhana","Buldhana"),
            ("Bagalkot","Bagalkot"),
            ("Bengaluru","Bengaluru"),
            ("Belagavi","Belagavi"),
            ("Ballari","Ballari"),
            ("Bidar","Bidar"),
            ("Chittoor","Chittoor"),
            ("Chandrapur","Chandrapur"),
            ("Chamarajanagar","Chamarajanagar"),
            ("Chikballapur","Chikballapur"),
            ("Chikkamagaluru","Chikkamagaluru"),
            ("Chitradurga","Chitradurga"),
            ("Chengalpattu","Chengalpattu"),
            ("Chennai","Chennai"),
            ("Coimbatore","Coimbatore"),
            ("Cuddalore","Cuddalore"),
            ("Dharmapuri","Dharmapuri"),
            ("Dindigul","Dindigul"),
            ("Dakshina Kannada","Dakshina Kannada"),
            ("Davanagere","Davanagere"),
            ("Dharwad","Dharwad"),
            ("Dhule","Dhule"),
            ("East Godavari","East Godavari"),
            ("Ernakulam","Ernakulam"),
            ("Erode","Erode"),
            ("Gadchiroli","Gadchiroli"),
            ("Gondia","Gondia"),
            ("Guntur","Guntur"),
            ("Gadag","Gadag"),
            ("Hingoli","Hingoli"),
            ("Hassan","Hassan"),
            ("Haveri","Haveri"),
            ("Idukki","Idukki"),
            ("Jalgaon","Jalgaon"),
            ("Jalna","Jalna"),
            ("Kolhapur","Kolhapur"),
            ("Krishna","Krishna"),
            ("Kurnool","Kurnool"),
            ("Kalaburagi","Kalaburagi"),
            ("Kodagu","Kodagu"),
            ("Kolar","Kolar"),
            ("Koppal","Koppal"),
            ("Kallakurichi","Kallakurichi"),
            ("Kanchipuram","Kanchipuram"),
            ("Kannur","Kannur"),
            ("Kanyakumari","Kanyakumari"),
            ("Karur","Karur"),
            ("Kasaragod","Kasaragod"),
            ("Kollam","Kollam"),
            ("Kottayam","Kottayam"),
            ("Kozhikode","Kozhikode"),
            ("Krishnagiri","Krishnagiri"),
            ("Latur","Latur"),
            ("Mandya","Mandya"),
            ("Mysuru","Mysuru"),
            ("Mumbai City","Mumbai City"),
            ("Mumbai Suburban","Mumbai Suburban"),
            ("Madurai","Madurai"),
            ("Malappuram","Malappuram"),
            ("Nagapattinam","Nagapattinam"),
            ("Namakkal","Namakkal"),
            ("Nilgris","Nilgris"),
            ("Nagpur","Nagpur"),
            ("Nanded","Nanded"),
            ("Nandurbar","Nandurbar"),
            ("Nashik","Nashik"),
            ("Osmanabad","Osmanabad"),
            ("Prakasam","Prakasam"),
            ("Palghar","Palghar"),
            ("Parbhani","Parbhani"),
            ("Pune","Pune"),
            ("Perambalur","Perambalur"),
            ("Pudukkottai","Pudukkottai"),
            ("Palakkad","Palakkad"),
            ("Pathanamthitta","Pathanamthitta"),
            ("Ramanathapuram","Ramanathapuram"),
            ("Ranipet","Ranipet"),
            ("Raichur","Raichur"),
            ("Ramanagara","Ramanagara"),
            ("Raigad","Raigad"),
            ("Ratnagiri","Ratnagiri"),
            ("Srikakulam","Srikakulam"),
            ("Sri Potti Sriramulu Nellore","Sri Potti Sriramulu Nellore"),
            ("Sangli","Sangli"),
            ("Satara","Satara"),
            ("Sindhudurg","Sindhudurg"),
            ("Solapur","Solapur"),
            ("Shivamogga","Shivamogga"),
            ("Salem","Salem"),
            ("Sivaganga","Sivaganga"),
            ("Tenkashi","Tenkashi"),
            ("Theni","Theni"),
            ("Thanjavur","Thanjavur"),
            ("Thoothukudi","Thoothukudi"),
            ("Tiruchirappalli","Tiruchirappalli"),
            ("Tirupathur","Tirupathur"),
            ("Tirunelveli","Tirunelveli"),
            ("Tiruvallur","Tiruvallur"),
            ("Tiruppur","Tiruppur"),
            ("Tiruvarur","Tiruvarur"),
            ("Tiruvannamalai","Tiruvannamalai"),
            ("Thiruvananthapuram","Thiruvananthapuram"),
            ("Thrissur","Thrissur"),
            ("Tumakuru","Tumakuru"),
            ("Thane","Thane"),
            ("Udupi","Udupi"),
            ("Uttara Kannada","Uttara Kannada"),
            ("Visakhapatnam","Visakhapatnam"),
            ("Vijayapur","Vijayapur"),
            ("Vizianagaram","Vizianagaram"),
            ("West Godavari","West Godavari"),
            ("Wardha","Wardha"),
            ("Washim","Washim"),
            ("Wayanad","Wayanad"),
            ("Yavatmal","Yavatmal"),
            ("YSR District, Kadapa (Cuddapah)","YSR District, Kadapa (Cuddapah)"),
            ("Yadgir","Yadgir"),
            ("Vellore","Vellore"),
            ("Viluppuram","Viluppuram"),
            ("Virudhanagar","Virudhanagar"),
)

APPOINTMENT_DAYS = (
    ("monday", "Monday"),
    ("tuesday", "Tuesday"),
    ("wednesday", "Wednesday"),
    ("thursday", "Thursday"),
    ("friday", "Friday"),
    ("saturday", "Saturday"),
    ("sunday", "Sunday"),
)

AD_SOURCE = (
    ("amber display", "Amber Display"),
    ("amber fb", "Amber FB"),
    ("amber remark", "Amber Remark"),
    ("amber search", "Amber Search"),
    ("amber yt", "Amber YT"),
    ("display", "Display"),
    ("remarketing", "Remarketing"),
    ("search", "Search"),
    ("video", "Video"),
)

JOB_TITLE = (
    ("p architect", "P Architect"),
    ("architect", "Architect"),
    ("junior architect", "Junior Architect"),
    ("project coordinator", "Project coordinator"),
    ("electrical consultant", "Electrical Consultant"),
    ("electrical contractor", "Electrical Contractor"),
    ("Interior Designer", "Interior Designer"),
    ("Electrician", "Electrician"),
)

PRIORITY = (
    ("high", "High"),
    ("medium", "Medium"),
    ("low", "Low"),
    ("normal", "Normal"),
)

INDUSTRY = (
    ("Architect's Firm", "Architect's Firm"),
    ("Customer", "Customer"),
    ("Interior Designer's Firm", "Interior Designer's Firm"),
    ("Electrical Consultant / MEP", "Electrical Consultant / MEP"),
    ("Electrical Contractors", "Electrical Contractors"),
    ("Electrical Shop Owner", "Electrical Shop Owner"),
    ("Civil Engineer", "Civil Engineer"),
    ("Civil Contractors", "Civil Contractors"),
    ("Premium Electrician", "Premium Electrician"),
    ("Small Scale Builders", "Small Scale Builders"),
    ("Large Scale Builders", "Large Scale Builders"),
    ("Dealer", "Dealer"),
    ("Electrician", "Electrician"),
    ("General Workers", "General Workers"),
    ("Integrators", "Integrators"),
    ("PMC", "PMC"),
)

TIER = (
    ("Tier A+", "Tier A+"),
    ("Tier A", "Tier A"),
    ("Tier B", "Tier B"),
    ("Tier C", "Tier C"),
)

LEAD_RESPONSE = (
    ("High Interest", "High Interest"),
    ("Medium Interest", "Medium Interest"),
    ("Low Interest", "Low Interest"),
    ("Neutral", "Neutral"),
    ("Not Interested", "Not Interested"),
)

CURRENCY = (
    ("INR", "INR"),
)
